//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MettleSystems.dashCommerce.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MettleSystems.dashCommerce.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null or empty string..
        /// </summary>
        internal static string ArgumentException {
            get {
                return ResourceManager.GetString("ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type provided must be an Enum..
        /// </summary>
        internal static string ArgumentMustBeAnEnum {
            get {
                return ResourceManager.GetString("ArgumentMustBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be greater than 0..
        /// </summary>
        internal static string ArgumentMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object &apos;{0}&apos; is not marked as [Serializable()] or does not implement ISerializable..
        /// </summary>
        internal static string ArgumentMustBeSerializable {
            get {
                return ResourceManager.GetString("ArgumentMustBeSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null..
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurationName length cannot be 0..
        /// </summary>
        internal static string ConfigurationNameLength {
            get {
                return ResourceManager.GetString("ConfigurationNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurationName cannot be null..
        /// </summary>
        internal static string ConfigurationNameNotNull {
            get {
                return ResourceManager.GetString("ConfigurationNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigurationObject cannot be null..
        /// </summary>
        internal static string ConfigurationObjectNotNull {
            get {
                return ResourceManager.GetString("ConfigurationObjectNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object &apos;{0}&apos; is not marked as [Serializable()], does not implement ISerializable, or is not a subclass of ConfigurationSection..
        /// </summary>
        internal static string ConfigurationObjectTypeInvalid {
            get {
                return ResourceManager.GetString("ConfigurationObjectTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigurationType.{0} is incompatible with this data store..
        /// </summary>
        internal static string ConfigurationTypeInvalid {
            get {
                return ResourceManager.GetString("ConfigurationTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigurationType.{0} - UserId must not be 0..
        /// </summary>
        internal static string ConfigurationUserIdNotZero {
            get {
                return ResourceManager.GetString("ConfigurationUserIdNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is not in enumeration. Enumeration Type: {0}. Argument Provided: {1}..
        /// </summary>
        internal static string EnumDefinitionException {
            get {
                return ResourceManager.GetString("EnumDefinitionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be null..
        /// </summary>
        internal static string ObjectNullException {
            get {
                return ResourceManager.GetString("ObjectNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object type. Type Expected: {0}. Type Provided: {1}..
        /// </summary>
        internal static string ObjectTypeException {
            get {
                return ResourceManager.GetString("ObjectTypeException", resourceCulture);
            }
        }
    }
}
