//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MettleSystems.dashCommerce.Store {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MettleSystems.dashCommerce.Store.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill To:.
        /// </summary>
        internal static string BillTo {
            get {
                return ResourceManager.GetString("BillTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon:.
        /// </summary>
        internal static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Price:.
        /// </summary>
        internal static string hdrExtendedPrice {
            get {
                return ResourceManager.GetString("hdrExtendedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string hdrItemName {
            get {
                return ResourceManager.GetString("hdrItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Number.
        /// </summary>
        internal static string hdrItemNumber {
            get {
                return ResourceManager.GetString("hdrItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string hdrPrice {
            get {
                return ResourceManager.GetString("hdrPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string hdrQuantity {
            get {
                return ResourceManager.GetString("hdrQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error has occurred: {0}.
        /// </summary>
        internal static string lblCriticalError {
            get {
                return ResourceManager.GetString("lblCriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order charged..
        /// </summary>
        internal static string OrderCharged {
            get {
                return ResourceManager.GetString("OrderCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date:.
        /// </summary>
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Items:.
        /// </summary>
        internal static string OrderItems {
            get {
                return ResourceManager.GetString("OrderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number:.
        /// </summary>
        internal static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order refunded..
        /// </summary>
        internal static string OrderRefunded {
            get {
                return ResourceManager.GetString("OrderRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status:.
        /// </summary>
        internal static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information:.
        /// </summary>
        internal static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method:.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;
        ///    &lt;Modulus&gt;2t81wME/0DhWuIrbzdeCrEXi5k7YkCzU9SL+LpOdfOub9WfbHURjqSC9Z04LvyFj0Kq04EzL1z74RoV+IR1pC8eYP31uvxz8GUHXYxQygPgKjTJgq2l0z2Fg5q6dCPiA89wefVfluZWhgdx7HuXSDA/9hUCeryI+GPwAySFPIs8=&lt;/Modulus&gt;
        ///    &lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping and Billing Information:.
        /// </summary>
        internal static string ShippingAndBilling {
            get {
                return ResourceManager.GetString("ShippingAndBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping &amp; Handling:.
        /// </summary>
        internal static string ShippingAndHandling {
            get {
                return ResourceManager.GetString("ShippingAndHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Method:.
        /// </summary>
        internal static string ShippingMethod {
            get {
                return ResourceManager.GetString("ShippingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship To:.
        /// </summary>
        internal static string ShipTo {
            get {
                return ResourceManager.GetString("ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal:.
        /// </summary>
        internal static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax:.
        /// </summary>
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Code:.
        /// </summary>
        internal static string TransactionCode {
            get {
                return ResourceManager.GetString("TransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete default provider. Please select a different default provider and then remove this provider..
        /// </summary>
        internal static string UnableToDeleteDefaultProvider {
            get {
                return ResourceManager.GetString("UnableToDeleteDefaultProvider", resourceCulture);
            }
        }
    }
}
