//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the WarpSpeed Model Generator 
//		 The WarpSpeed Model Generator is Copyright 2008-2009 Mettle Systems LLC
//     All rights reserved.
//     Runtime Version: 1.0.0.17034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using NHibernate.Validator.Constraints;

namespace MettleSystems.MultiTenant.Core.Models.Entities {

	[Serializable]
	[GeneratedCode("WarpSpeed Model Generator", "1.0.0.17034")]
	public partial class Client {

		#region Properties
    			
			public virtual int ClientId { get; set;}
	    			
			[NotNullNotEmpty]
			[Length(Max=50)]
			public virtual string Name { get; set; }
	                  
    public virtual IList<ClientApplicationMap> ClientApplicationMaps { get; set; }
        

		#endregion
		

	}
}