//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MettleSystems.dashCommerce.Web.controls.content.products {
    
    
    public partial class ProductItem {
        
        /// <summary>
        /// hlImageLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.HyperLink hlImageLink;
        
        /// <summary>
        /// hlProduct control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.HyperLink hlProduct;
        
        /// <summary>
        /// lblRetailPrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblRetailPrice;
        
        /// <summary>
        /// lblOurPrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblOurPrice;
        
        /// <summary>
        /// ajaxRating control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.Rating ajaxRating;
    }
}
