//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MettleSystems.dashCommerce.Web.admin.controls.sitesettings {
    
    
    public partial class seosettings {
        
        /// <summary>
        /// pnlSeo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlSeo;
        
        /// <summary>
        /// lblSiteKeywords control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblSiteKeywords;
        
        /// <summary>
        /// helpSiteKeywords control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.HelpLink helpSiteKeywords;
        
        /// <summary>
        /// txtSiteKeywords control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSiteKeywords;
        
        /// <summary>
        /// lblSiteDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblSiteDescription;
        
        /// <summary>
        /// helpSiteDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.HelpLink helpSiteDescription;
        
        /// <summary>
        /// txtSiteDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSiteDescription;
        
        /// <summary>
        /// lblCopyrightText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblCopyrightText;
        
        /// <summary>
        /// txtCopyrightText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCopyrightText;
        
        /// <summary>
        /// helpCopyrightText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.HelpLink helpCopyrightText;
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Button btnSave;
    }
}
