//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace MettleSystems.dashCommerce.Store.dashCommerceTaxSvc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TaxBasicSoap", Namespace="https://webservices.dashcommerce.com/tax/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractRecordOfAsBasic))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractRecordOfCanada))]
    public partial class TaxBasic : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTaxRateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TaxBasic() {
            this.Url = global::MettleSystems.dashCommerce.Store.Properties.Settings.Default.MettleSystems_dashCommerce_Store_dashCommerceTaxSvc_TaxBasic;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTaxRateCompletedEventHandler GetTaxRateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservices.dashcommerce.com/tax/GetTaxRate", RequestNamespace="https://webservices.dashcommerce.com/tax/", ResponseNamespace="https://webservices.dashcommerce.com/tax/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaxResponse GetTaxRate(TaxRequest taxRequest) {
            object[] results = this.Invoke("GetTaxRate", new object[] {
                        taxRequest});
            return ((TaxResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetTaxRateAsync(TaxRequest taxRequest) {
            this.GetTaxRateAsync(taxRequest, null);
        }
        
        /// <remarks/>
        public void GetTaxRateAsync(TaxRequest taxRequest, object userState) {
            if ((this.GetTaxRateOperationCompleted == null)) {
                this.GetTaxRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTaxRateOperationCompleted);
            }
            this.InvokeAsync("GetTaxRate", new object[] {
                        taxRequest}, this.GetTaxRateOperationCompleted, userState);
        }
        
        private void OnGetTaxRateOperationCompleted(object arg) {
            if ((this.GetTaxRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTaxRateCompleted(this, new GetTaxRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public partial class TaxRequest {
        
        private CountryCode countryCodeField;
        
        private string regionCodeField;
        
        private License licenseField;
        
        /// <remarks/>
        public CountryCode CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RegionCode {
            get {
                return this.regionCodeField;
            }
            set {
                this.regionCodeField = value;
            }
        }
        
        /// <remarks/>
        public License License {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public enum CountryCode {
        
        /// <remarks/>
        UnitedStates,
        
        /// <remarks/>
        Canada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public partial class License {
        
        private string licenseKeyField;
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        public string LicenseKey {
            get {
                return this.licenseKeyField;
            }
            set {
                this.licenseKeyField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActiveRecordOfAsBasic))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AsBasic))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public abstract partial class AbstractRecordOfAsBasic {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AsBasic))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public abstract partial class ActiveRecordOfAsBasic : AbstractRecordOfAsBasic {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public partial class AsBasic : ActiveRecordOfAsBasic {
        
        private string zipCodeField;
        
        private string stateAbbrevField;
        
        private string countyNameField;
        
        private string cityNameField;
        
        private string stateSalesTaxField;
        
        private string stateUseTaxField;
        
        private string countySalesTaxField;
        
        private string countyUseTaxField;
        
        private string citySalesTaxField;
        
        private string cityUseTaxField;
        
        private string totalSalesTaxField;
        
        private string totalUseTaxField;
        
        private string taxShippingAloneField;
        
        private string taxShippingAndHandlingTogetherField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StateAbbrev {
            get {
                return this.stateAbbrevField;
            }
            set {
                this.stateAbbrevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StateSalesTax {
            get {
                return this.stateSalesTaxField;
            }
            set {
                this.stateSalesTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StateUseTax {
            get {
                return this.stateUseTaxField;
            }
            set {
                this.stateUseTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountySalesTax {
            get {
                return this.countySalesTaxField;
            }
            set {
                this.countySalesTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountyUseTax {
            get {
                return this.countyUseTaxField;
            }
            set {
                this.countyUseTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CitySalesTax {
            get {
                return this.citySalesTaxField;
            }
            set {
                this.citySalesTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CityUseTax {
            get {
                return this.cityUseTaxField;
            }
            set {
                this.cityUseTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalSalesTax {
            get {
                return this.totalSalesTaxField;
            }
            set {
                this.totalSalesTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalUseTax {
            get {
                return this.totalUseTaxField;
            }
            set {
                this.totalUseTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TaxShippingAlone {
            get {
                return this.taxShippingAloneField;
            }
            set {
                this.taxShippingAloneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TaxShippingAndHandlingTogether {
            get {
                return this.taxShippingAndHandlingTogetherField;
            }
            set {
                this.taxShippingAndHandlingTogetherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActiveRecordOfCanada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Canada))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public abstract partial class AbstractRecordOfCanada {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Canada))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public abstract partial class ActiveRecordOfCanada : AbstractRecordOfCanada {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public partial class Canada : ActiveRecordOfCanada {
        
        private string abbrevField;
        
        private string provinceNameField;
        
        private string gstField;
        
        private string pstField;
        
        private string totalField;
        
        private string taxShippingHandlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Abbrev {
            get {
                return this.abbrevField;
            }
            set {
                this.abbrevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProvinceName {
            get {
                return this.provinceNameField;
            }
            set {
                this.provinceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Gst {
            get {
                return this.gstField;
            }
            set {
                this.gstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Pst {
            get {
                return this.pstField;
            }
            set {
                this.pstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TaxShippingHandling {
            get {
                return this.taxShippingHandlingField;
            }
            set {
                this.taxShippingHandlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public partial class ExceptionWS {
        
        private string exceptionTypeNameField;
        
        private string messageField;
        
        private string sourceField;
        
        private string stackTraceField;
        
        private string helpLinkField;
        
        /// <remarks/>
        public string ExceptionTypeName {
            get {
                return this.exceptionTypeNameField;
            }
            set {
                this.exceptionTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        public string HelpLink {
            get {
                return this.helpLinkField;
            }
            set {
                this.helpLinkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.dashcommerce.com/tax/")]
    public partial class TaxResponse {
        
        private ExceptionWS[] exceptionCollectionField;
        
        private Canada canadaTaxDetailsField;
        
        private AsBasic uSTaxDetailsField;
        
        private decimal totalSalesTaxField;
        
        /// <remarks/>
        public ExceptionWS[] ExceptionCollection {
            get {
                return this.exceptionCollectionField;
            }
            set {
                this.exceptionCollectionField = value;
            }
        }
        
        /// <remarks/>
        public Canada CanadaTaxDetails {
            get {
                return this.canadaTaxDetailsField;
            }
            set {
                this.canadaTaxDetailsField = value;
            }
        }
        
        /// <remarks/>
        public AsBasic USTaxDetails {
            get {
                return this.uSTaxDetailsField;
            }
            set {
                this.uSTaxDetailsField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalSalesTax {
            get {
                return this.totalSalesTaxField;
            }
            set {
                this.totalSalesTaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTaxRateCompletedEventHandler(object sender, GetTaxRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTaxRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTaxRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaxResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaxResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591