//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MettleSystems.dashCommerce.Web {
    
    
    public partial class checkout {
        
        /// <summary>
        /// leftNavigation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Web.controls.navigation.leftnavigation leftNavigation;
        
        /// <summary>
        /// upDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress upDisplay;
        
        /// <summary>
        /// upCheckout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upCheckout;
        
        /// <summary>
        /// pnlBillingAddressDisplayTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlBillingAddressDisplayTitle;
        
        /// <summary>
        /// lblBillingAddressTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblBillingAddressTitle;
        
        /// <summary>
        /// pnlBillingAddressDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlBillingAddressDisplay;
        
        /// <summary>
        /// billingAddressDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Web.controls.addressdisplay billingAddressDisplay;
        
        /// <summary>
        /// pnlShippingAddressDisplayTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlShippingAddressDisplayTitle;
        
        /// <summary>
        /// lblShippingAddressTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblShippingAddressTitle;
        
        /// <summary>
        /// pnlShippingAddressDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlShippingAddressDisplay;
        
        /// <summary>
        /// shippingAddressDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Web.controls.addressdisplay shippingAddressDisplay;
        
        /// <summary>
        /// pnlShippingMethodDisplayTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlShippingMethodDisplayTitle;
        
        /// <summary>
        /// lblShippingMethodTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblShippingMethodTitle;
        
        /// <summary>
        /// pnlShippingMethodDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlShippingMethodDisplay;
        
        /// <summary>
        /// lblShippingMethodDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblShippingMethodDisplay;
        
        /// <summary>
        /// pnlCouponInformationDisplayTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlCouponInformationDisplayTitle;
        
        /// <summary>
        /// lblCouponInformationTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblCouponInformationTitle;
        
        /// <summary>
        /// pnlCouponInformationDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlCouponInformationDisplay;
        
        /// <summary>
        /// lblCouponInformationDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblCouponInformationDisplay;
        
        /// <summary>
        /// pnlPaymentInformationDisplayTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlPaymentInformationDisplayTitle;
        
        /// <summary>
        /// lblPaymentInformationTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblPaymentInformationTitle;
        
        /// <summary>
        /// pnlPaymentInformationDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlPaymentInformationDisplay;
        
        /// <summary>
        /// lblCreditCardType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblCreditCardType;
        
        /// <summary>
        /// pnlCreditCardInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlCreditCardInfo;
        
        /// <summary>
        /// lblMaskedCreditCardNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblMaskedCreditCardNumber;
        
        /// <summary>
        /// lblCreditCardExpirationDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblCreditCardExpirationDate;
        
        /// <summary>
        /// cpeBillingAddressDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeBillingAddressDisplay;
        
        /// <summary>
        /// cpeShippingAddressDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeShippingAddressDisplay;
        
        /// <summary>
        /// cpeShippingMethodDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeShippingMethodDisplay;
        
        /// <summary>
        /// cpeCouponInformationDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeCouponInformationDisplay;
        
        /// <summary>
        /// cpePaymentInformationDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender cpePaymentInformationDisplay;
        
        /// <summary>
        /// acCheckout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.Accordion acCheckout;
        
        /// <summary>
        /// acpBillingAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AccordionPane acpBillingAddress;
        
        /// <summary>
        /// lblBillingInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblBillingInformation;
        
        /// <summary>
        /// billingAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Web.controls.address billingAddress;
        
        /// <summary>
        /// chkUseForShipping control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.CheckBox chkUseForShipping;
        
        /// <summary>
        /// btnBillingAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Button btnBillingAddress;
        
        /// <summary>
        /// acpShippingAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AccordionPane acpShippingAddress;
        
        /// <summary>
        /// lblShippingInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblShippingInformation;
        
        /// <summary>
        /// shippingAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Web.controls.address shippingAddress;
        
        /// <summary>
        /// btnShippingAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Button btnShippingAddress;
        
        /// <summary>
        /// acpShippingMethod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AccordionPane acpShippingMethod;
        
        /// <summary>
        /// lblShippingMethod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblShippingMethod;
        
        /// <summary>
        /// rblShippingOptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rblShippingOptions;
        
        /// <summary>
        /// btnShippingMethod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Button btnShippingMethod;
        
        /// <summary>
        /// acpCoupon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AccordionPane acpCoupon;
        
        /// <summary>
        /// lblCouponInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblCouponInformation;
        
        /// <summary>
        /// lblCouponCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblCouponCode;
        
        /// <summary>
        /// txtCouponCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCouponCode;
        
        /// <summary>
        /// btnCoupon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Button btnCoupon;
        
        /// <summary>
        /// acpPaymentInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AccordionPane acpPaymentInformation;
        
        /// <summary>
        /// lblPaymentInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblPaymentInformation;
        
        /// <summary>
        /// lblPaymentMethod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblPaymentMethod;
        
        /// <summary>
        /// ddlCreditCardType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCreditCardType;
        
        /// <summary>
        /// pnlCreditCardInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlCreditCardInformation;
        
        /// <summary>
        /// lblCreditCardNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblCreditCardNumber;
        
        /// <summary>
        /// txtCreditCardNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCreditCardNumber;
        
        /// <summary>
        /// RequiredFieldValidator7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.RequiredFieldValidator RequiredFieldValidator7;
        
        /// <summary>
        /// imgSSL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image imgSSL;
        
        /// <summary>
        /// lblCreditCardSecurityNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblCreditCardSecurityNumber;
        
        /// <summary>
        /// txtCreditCardSecurityNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCreditCardSecurityNumber;
        
        /// <summary>
        /// RequiredFieldValidator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.RequiredFieldValidator RequiredFieldValidator1;
        
        /// <summary>
        /// pnlDebitCardInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Panel pnlDebitCardInformation;
        
        /// <summary>
        /// lblIssueNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblIssueNumber;
        
        /// <summary>
        /// txtDebitCardIssueNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDebitCardIssueNumber;
        
        /// <summary>
        /// lblStart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblStart;
        
        /// <summary>
        /// ddlDebitCardStartMonth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlDebitCardStartMonth;
        
        /// <summary>
        /// ddlDebitCardStartYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlDebitCardStartYear;
        
        /// <summary>
        /// lblExpiration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblExpiration;
        
        /// <summary>
        /// ddlCreditCardExpirationMonth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCreditCardExpirationMonth;
        
        /// <summary>
        /// ddlCreditCardExpirationYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCreditCardExpirationYear;
        
        /// <summary>
        /// btnPaymentMethod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Button btnPaymentMethod;
        
        /// <summary>
        /// acpOrderReview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AccordionPane acpOrderReview;
        
        /// <summary>
        /// lblOrderReview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblOrderReview;
        
        /// <summary>
        /// orderSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Web.controls.ordersummary orderSummary;
        
        /// <summary>
        /// btnProcessOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Button btnProcessOrder;
        
        /// <summary>
        /// imgError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image imgError;
        
        /// <summary>
        /// lblError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MettleSystems.dashCommerce.Controls.Label lblError;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new MettleSystems.dashCommerce.Web.site Master {
            get {
                return ((MettleSystems.dashCommerce.Web.site)(base.Master));
            }
        }
    }
}
